variable "external_tg_name" {}
variable "external_tg_port" {}
variable "external_tg_protocol" {}
variable "external_vpc_id" {}
variable "external_lb_name" {}
variable "ext_internal" {}
variable "external_lb_type" {}
variable "external_lb_sg" {}
variable "external_lb_subnet" {}
variable "external_lb_listener_port" {}
variable "external_lb_listener_protocol" {}
variable "internal_tg_name" {}
variable "internal_tg_port" {}
variable "internal_tg_protocol" {}
variable "internal_vpc_id" {}
variable "internal_lb_name" {}
variable "int_internal" {}
variable "internal_lb_type" {}
variable "internal_lb_sg" {}
variable "internal_lb_subnet" {}
variable "internal_lb_listener_port" {}
variable "internal_lb_listener_protocol" {}