variable "region" {}
variable "vpc_cidr" {}
variable "project_name" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "role_name" {}

variable "storage" {}
variable "db_name" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "db_username" {}
variable "db_password" {}
variable "skip_final_snapshot" {}
variable "multi_az" {}
variable "external_tg_name" {}
variable "external_tg_port" {}
variable "external_tg_protocol" {}
variable "external_lb_name" {}
variable "ext_internal" {}
variable "external_lb_type" {}
variable "external_lb_listener_port" {}
variable "external_lb_listener_protocol" {}
variable "internal_tg_name" {}
variable "internal_tg_port" {}
variable "internal_tg_protocol" {}
variable "internal_lb_name" {}
variable "int_internal" {}
variable "internal_lb_type" {}
variable "internal_lb_listener_port" {}
variable "internal_lb_listener_protocol" {}
variable "app_tier_launch_template_name" {}
variable "app_tier_launch_template_description" {}
variable "app_tier_launch_template_image_id" {}
variable "app_tier_launch_template_instance_type" {}
variable "app_tier_ASG_name" {}
variable "app_tier_min_size" {}
variable "app_tier_max_size" {}
variable "app_tier_desired_capacity" {}
variable "app_tier_ASG_force_delete" {}
variable "app_tier_ASG_health_check_type" {}
variable "web_tier_launch_template_name" {}
variable "web_tier_launch_template_description" {}
variable "web_tier_launch_template_image_id" {}
variable "web_tier_launch_template_instance_type" {}
variable "web_tier_ASG_name" {}
variable "web_tier_min_size" {}
variable "web_tier_max_size" {}
variable "web_tier_desired_capacity" {}
variable "web_tier_ASG_force_delete" {}
variable "web_tier_ASG_health_check_type" {}